
techo: columnas paredes
	touch techo

columnas: cimiento
	touch columnas

paredes: cimiento
	touch paredes

cimiento:
	touch cimiento



#Una vez entendido lo anterior vemos clean
clean:
	rm -f techo columnas paredes cimiento

